### ISSUE TITLE
Assignment fails in platform 

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-planner#1475]
http://www.screencast.com/t/gzgj3qprkXF7

**Comment by sbose78** [comment]
Even though the core commit has been reverted , I wanted to summarize the fix tried out by @nimishamukherjee for future use.

- the updated API Structure had the identityID in its response.
- the PATCH request sent out during assignment needed to send out the above identityID value instead of the UserID value.
- after making the changes locally on planner, it worked.
