### ISSUE TITLE
Cannot view work items of all types on board

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-planner#1494]
http://www.screencast.com/t/vF0qzaBi3aJ

**Comment by catrobson** [comment]
@pmuir this was an agreed upon restriction for Summit because the # of rows could be different for the status of each work item type.  We would then need to know the logic of which type of item you're working with to know which columns you could move them to, and we also wouldn't know which order to put the columns in where they don't map across work item types.  Due to these complexities, we have restricted the board view to only one work item type at a time for now.

**Comment by nimishamukherjee** [comment]
Can we close this @pmuir?

**Comment by pmuir** [comment]
Yes.
