### ISSUE TITLE
Comments Delete looks broken 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1596]
Comments Delete looks broken 

Steps to Reproduce 
- Delete a comment 
The Delete Pop up will cover the entire screen !
![screenshot from 2017-04-12 13-56-30](https://cloud.githubusercontent.com/assets/19172870/24948441/f561b28e-1f87-11e7-9bcf-4e49be8d95d9.png)

**Comment by naina-verma** [comment]
@deb can you please look into it

**Comment by debloper** [comment]
I'll need to check how the z-index on the backdrop broke again. Thanks for reporting.

**Comment by mindreeper2420** [comment]
@debloper @naina-verma there are massive conflicts with the z-indexes and the fact that the Detail Panel covered up the user dropdown menu (top right menu). Are the modals using the default z-indexes from PF? We shouldn't need to increment the z-indexes by 100+ layers at a time.

**Comment by debloper** [comment]
The modal is a 3rd party module that we have no control over (apart from trying to contribute there and hope the maintainer accepts the change, at the risk of that change affecting everyone else using the module and probably breaking their code). Also, as it is not in our hand to specify the z-index of the backdrop, we can't follow the PF defaults here, so that's out of the question.

We can address this problem in these few ways:

* **Least troubling, but messy:** Let's revert back the 1050 z-index on the modal-dialog itself, and put a higher value on anything else that it blocks.
* **Troublesome and lengthy, but effective:** Use different modal-module that's not as shitty (affecting all other modals we have).
* **Troublesome and weird, but effective:** Fork and maintain a separate fixed version of the module by ourselves, where the z-indexes are much saner.
* **Troublesome and unlikely, but effective:** Send a patch to that module's upstream and hope it gets accepted (but most likely it wont be accepted, cause it can break all other applications using it).

Also, while making the changes, please ensure not to remove the contexts. If you want to comment a code block out, there's no need for removing the code-contexts that helps identify the regression.

**Comment by debloper** [comment]
While we're at it, I've just checked that many people have complained about this weirdness in that module, and it's [underway some changes](https://github.com/pleerock/ngx-modal/pulls?utf8=%E2%9C%93&q=is%3Apr%20backdrop).

We now have an *option* to remove the backdrop (so, no forced z-indexes will be necessary, bu we wont have the dark background behind the modal either), if that makes things easier.

**Comment by michaelkleinhenz** [comment]
Check with UX and find out what they recommend.

**Comment by catrobson** [comment]
The dark background behind the modal is required in order to allow the user to make some sense of the screen when a modal appears - the screen is too busy to have a modal without this, so I don't think removing backdrop is an option for us.

**Comment by mindreeper2420** [comment]
as a starting point, the `.dropdown` z-index is set at 1000. Ideally, there would be a break at that point - page content (iteration panel, detail panel, work item list, etc.) would be under 1000 and modals would be above 1000.

Currently, Iteration modal (for creating and editing) has `z-index: 1050;`, which is in line with the ideals. This is the default for the `.modal` class of PatternFly, which works without issue.

What I've noticed is that the Delete Modal is nested inside of the Detail Panel and is not laid out/fired off in the same manner as the other modals. If you update the Delete Modal to match that of the Iteration Modal, then the collisions should be fixed.

**Comment by naina-verma** [comment]
@debloper , https://redhat.invisionapp.com/share/Q6AAQVO8X#/screens/217205690 please find this expected invison link !

**Comment by SMahil** [comment]
@debloper Make the delete modal as separate component. You can refer the Iteration Modal.

**Comment by debloper** [comment]
Reviewing through the iteration component's implementation of Modals, it's not much different from the comment delete modal by the fact how it affects the DOM tree (apart from apparent modularity and dynamic composure, which is not needed in this case.

As we can see the base style is also same for the modal class:
## Iteration modal:
![screenshot from 2017-04-27 16-53-26](https://cloud.githubusercontent.com/assets/536060/25481384/8c53982c-2b6a-11e7-8835-5497da63108c.png)
## Delete comment modal:
![screenshot from 2017-04-27 16-54-34](https://cloud.githubusercontent.com/assets/536060/25481392/94c1e0a4-2b6a-11e7-9014-349194cdff76.png)

The difference, however, lies within how the parent elements are laid out. And in case of details component (the slide out panel from right) makes everything harder for this case. I'm looking into possible workarounds, but the iteration modal as reference doesn't provide a solution here.
