### ISSUE TITLE
Logging into prod-preview.openshift.io raises 400 (bad request) exception - No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1637]
After logging in, this exception is logged:

```
2sso.prod-preview.openshift.io/auth/realms/fabric8/broker/openshift-v3/token:1 GET https://sso.prod-preview.openshift.io/auth/realms/fabric8/broker/openshift-v3/token 400 (Bad request)
_home:1 XMLHttpRequest cannot load https://sso.prod-preview.openshift.io/auth/realms/fabric8/broker/openshift-v3/token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://prod-preview.openshift.io' is therefore not allowed access. The response had HTTP status code 400.
main.433d4a1….bundle.js:1 Unable to get OpenShift token Response {_body: ProgressEvent, status: 0, ok: false, statusText: "", headers: Headers…}

2sso.prod-preview.openshift.io/auth/realms/fabric8/broker/github/token:1 GET https://sso.prod-preview.openshift.io/auth/realms/fabric8/broker/github/token 400 (Bad request)
_home:1 XMLHttpRequest cannot load https://sso.prod-preview.openshift.io/auth/realms/fabric8/broker/github/token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://prod-preview.openshift.io' is therefore not allowed access. The response had HTTP status code 400.
```

**Comment by hectorj2f** [comment]
I am seeing a recurrent error in the `core` logs cause I cannot see anything at keycloak level rather than invalid token.

Search in the logs of core `level: "error" AND message: "*request method or response status code does not allow body*"`:
https://logs.rh-idev.openshift.com/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'project.dsaas-preview.51e07e7a-1597-11e7-ad87-0e6aaf341bbf.*',key:kubernetes.container_name,negate:!f,value:core),query:(match:(kubernetes.container_name:(query:core,type:phrase))))),index:'project.dsaas-preview.51e07e7a-1597-11e7-ad87-0e6aaf341bbf.*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'level:%20%22error%22%20AND%20message:%20%22*request%20method%20or%20response%20status%20code%20does%20not%20allow%20body*%22')),sort:!('@timestamp',desc))

**Comment by ldimaggi** [comment]
Moved to:

https://github.com/openshiftio/www.openshift.io/issues/83
