### ISSUE TITLE
Not possible to have work items of the same type linked via "relates to" link type

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#434]
At present, a user cannot link work items of type bug together via a "relates to" link type. I'd suggest that users always be able to link together work items of any type as "relates to." Is there a reason that we are blocking this link type? Thx!

**Comment by nimishamukherjee** [comment]
@kwk, @sanbornsen comments? Do we need UX's input here? Or is this more of an implementation restriction?

**Comment by kwk** [comment]
@ldimaggi you are right, it should be possible. Checking why that is. It would have been nice if the type-ahead doesn't show any items of the same type or if the link creation is prohibited when you click "link".

**Comment by kwk** [comment]
@ldimaggi the issue is valid because currently the "relates to" link type allows you to link any "planner item" to any "planner item". Even though any bug or feature is indeed also a "planner item" in the backend, the link creation cannot "understand" this until https://github.com/almighty/almighty-core/pull/602 is merged to fix https://github.com/almighty/almighty-core/issues/473 and can "properly" talk to the frontend.

**Comment by ldimaggi** [comment]
Closing as out of date - no longer an issue.
