### ISSUE TITLE
Unfiy the developer and production configs

### ISSUE THREAD

**Issue by kbsingh** [fabric8io/fabric8-planner#48]
There should'nt be a seperate config set for development v/s production configs and machine setup - most of the content needed in developer only stages should be abstracted out into either a run time config or collected from defaults at build time.

site specific content should be stripped out in a way that the CI infra, the pre-prod infra, the prod infra and the developer environ can influence them opportunisitically.

**Comment by joshuawilson** [comment]
@kbsingh The short answer is that most of the things in development are needed to debug and and work with the code. The prod step strips all that off and minifies and performs other clean up.

I'll go through all the build steps in the UI and list them if you need. We can then evaluate if we need to do something different. A lot of things were done without much planning in order to get the release out.

**Comment by michaelkleinhenz** [comment]
I think we are almost there already. With #40 done, the core URL is baked in on build time and there is no other configuration (yet). The webpack configs have to be cleaned up and I think we can unify webpack.dev.js and webpack.prod.js. The test stuff should run regardless if dev or prod is built, so we should go for eliminating webpack.test.js.
