### ISSUE TITLE
Two titles are displayed during the dialog based work item creation

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-planner#594]
- Click on +
- Select any type
- Enter work item title
- Hit enter or click on tick to save
- For a few seconds we see two titles

**Comment by debloper** [comment]
Took me a while to get to the roots of it.

This is regression of commit fb53a4480c7a1ceebfc77a2df23cdcbdb5e4b0ac, where `*ngIf="(loggedIn && headerEditable || !workItem.id)"` is essentially working as `*ngIf="((loggedIn && headerEditable) || !workItem.id)"`, meaning:

- It can be *truthy* even when `headerEditable` is false
  - So to say, when `workItem.id` is falsy
  - That is the case while creating a new WI
- This leads the header to show cause because `headerEditable` is false, as well as the edit title field to show as `workItem.id` is undefined
- This is resolved as soon as the API call `save` completes, returning `workItem.id`
- It generally takes 100-200ms for `save` to return during which time the bug occurs

Need discussion on how to handle this (don't wanna break the dialog based creation of work items trying to refactor it).

**Comment by debloper** [comment]
By checking `workItem.id` as the flag to identify whether a WI is in it's creation phase, will break the workflow as it's not a proof of creation. We should ideally set a new flag while initiating a WI creation, and use that instead for the DOM conditional/directives.

**Comment by debloper** [comment]
Please verify if [this change](https://github.com/debloper/almighty-ui/commit/0afc2dd5cf35646df969565d296ca6267d53601a) fixes the issue. I'll send a PR if it does.
