### ISSUE TITLE
"Assign to me" is not dynamic , when changed assignee during filter 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#608]
"Assign to me" is not dynamic , when changed assign during filter 

Video : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6CORU9jbTdzMWFpbHM/view?usp=sharing

Expected : 
- Apply Assign to me filter then only WI should be shown relevant to assign user who is logged in(Works fine)
- On changing/updating  assignee to dialog the , filtered list should be update with the current results.(Issue)
- When we create WI and user is inside filtered list ,there is no such assignee (showing in video), the filtered list should not show that WI in the current results.

**Comment by nimishamukherjee** [comment]
@fabric8io/uxd could you please let us know the experience in the following scenarios:
Scenario 1
1. Filter by "Assign to me"
2. Click on any of the work item and open it's detailed view
3. Un-assign the work item
The work item list needs to get updated. What happens to the detailed view - do we need to close it?

Scenario 2
1. On the list view, open a work item detailed view, which has not been "assigned to me"
2. While the detail view is open, click on Filter > "Assign to me"
3. The filtered list shows up
Question - what happens to the detailed view? Does it remain open? This work item will not show up in the filtered list as it has not been "Assigned to me".

**Comment by Mgranfie** [comment]
My feedback and questions in line below. Good catch on these scenarios
where we click away mid- edit or create on an open work item.

> @fabric8io/uxd <https://github.com/orgs/fabric8io/teams/uxd> could you
> please let us know the experience in the following scenarios:
> Scenario 1
>
>    1. Filter by "Assign to me" (mg)should this be "assigned" to me?
>    2. Click on any of the work item and open it's detailed view
>    3. Un-assign the work item
>    The work item list needs to get updated. What happens to the detailed
>    view - do we need to close it?
>
> (mg) Adam may want to contribute here... my thinking is that the user
clicks on the Unassign command. The list closes and the text next the the
field changes to Unassigned and the user clicks on the checkmark or x to
accept or cancel the change.

>
>
> Scenario 2
>
>    1. On the list view, open a work item detailed view, which has not
>    been "assigned to me"
>    2. While the detail view is open, click on Filter > "Assign to me"(mg)should
>    this be "assigned" to me?
>    3. The filtered list shows up
>    Question - what happens to the detailed view? Does it remain open?
>    This work item will not show up in the filtered list as it has not been
>    "Assigned to me".
>
> (mg) to me it sounds like if you invoke a filter, meaning change the
iteration selected on the left or a filter at the top or place focus in the
search field, the detailed work item should close, under those
circumstances.

Questions around this behavior:

1.  If a change is being made on the WI and has not been committed, one way
or the other, we have to flag that with an inline error or dialog,
depending on the interaction, and not close the detailed WI.

2. In situations where it might not matter, ie: assigning a WIL, I have
searched  and selected a WI link but not linked it yet, would this data
persist in the field, while the browser is in session, so that when a user
navigates back the data will be there? If we can't do this, we should throw
an error. on the linking part of the UI.

3.  Same consideration on comments...
a. When entering a comment and the user navigates away from the detailed
open WI. Do we persist the entry, can we, per browser session?
b. Editing a comment would throw an in line error and prevent the WI from
being closed.

4. Attaching an iteration (SJ jump in here)

I think that is all we have on the WI for now. If we all agree on these
rules, we can continue to take the solution into consideration, as we build
out the WI with more data.

If you can let us know which solutions might be possible and if this makes
sense, we can refine from here.

Thanks,
Monica
