### ISSUE TITLE
Managing Branches and PRs

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#672]
We might need a new way of managing the source and the branches to reduce the amount of work put into rebasing.

**Comment by aslakknutsen** [comment]
The maintainer, the person merging, should press the 'update branch' button as needed. No need for the PR sender to do this, because she/he doesn't know which order the maintainer is working in. The only reason for the PR sender to manually rebase is in the case of conflicts.

The PR sender should check the 'allow maintainer' access to the branch she/he is sending a PR from.
