### ISSUE TITLE
"Do-It" Button on Work Items in Detail View [2]

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#889]
# Description
As a user, I want to open a Che context for a Work Item from the Work Item detail view.

# Functional Acceptance Criteria
1. A Work Item includes fields with meta information used for linking to a Che context.
2. The new fields are internal only and are not displayed or being editable by the user.
3. If the fields are present (non empty), the Work Item detail view shows a link or button.
4. Clicking on the button opens Che in a new browser window using an URL constructed from the meta fields on the Work Item.

# Non-functional Acceptance Criteria
None.

**Note:** The exact nature of the extra field is to be defined. Also the way of creating the URL from the field values.

**Note:** This story currently only describes linking to Che. For other linkings, there will be a new architecture being developed later that is more flexible. The implementation done for this story can then be regarded legacy.

**Note:** The URL must be constructable **only** from the meta fields on the Work Item and static contents hardcoded in the Planner.

**Comment by pranavgore09** [comment]
[PR](https://github.com/almighty/almighty-core/pull/794) from core tells you `how` to get editor's URL, it's value is not yet finalised.
**Note:** Do not consume the value of URL to perform any testing.

**Comment by pranavgore09** [comment]
As per conversation in [PR](https://github.com/almighty/almighty-core/pull/794), UI team need to use `relationships->codebase->links->meta["edit"]` attribute to locate the `do-it-URL`. If this attribute is set then enable the `do it` button else not.
Core will not be giving value for this attribute because other modules are not yet ready to integrate that piece and strategies for the same are not yet finalised. Hence no code changes from `core` for this particular task.
